server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:
        format_sql: true
    show_sql: true